### ISSUE TITLE
Update alert channel panic

### ISSUE THREAD

**Issue by jojotong** [kubegems/kubegems#432]
```log
api fatal error: concurrent map iteration and map write
api
api goroutine 1940 [running]:                                                                                                                                                                                    api runtime.throw({0x5a49c52?, 0xffffffffffffff01?})                                                                                                                                                             api     /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:992 +0x71 fp=0xc005297118 sp=0xc0052970e8 pc=0x43ddb1                                                                                           api runtime.mapiternext(0x5359780?)                                                                                                                                                                              api     /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/map.go:871 +0x60a fp=0xc0052971a8 sp=0xc005297118 pc=0x41168a                                                                                            api k8s.io/apimachinery/pkg/apis/meta/v1.(*ObjectMeta).DeepCopyInto(0xc0050ea020, 0xc005c782a0)                                                                                                                  api     /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/apis/meta/v1/zz_generated.deepcopy.go:677 +0x9d1 fp=0xc005297410 sp=0xc0052971a8 pc=0xf2b591                                                     api k8s.io/api/core/v1.(*Secret).DeepCopyInto(0xc0050ea000, 0xc005c78280)                                                                                                                                        api     /home/runner/go/pkg/mod/k8s.io/api@v0.23.5/core/v1/zz_generated.deepcopy.go:4855 +0x113 fp=0xc005297658 sp=0xc005297410 pc=0x11ec9d3                                                                     api k8s.io/api/core/v1.(*Secret).DeepCopy(0xc0050ea000)                                                                                                                                                          api     /home/runner/go/pkg/mod/k8s.io/api@v0.23.5/core/v1/zz_generated.deepcopy.go:4892 +0x4d fp=0xc005297688 sp=0xc005297658 pc=0x11ed06d                                                                      api k8s.io/api/core/v1.(*Secret).DeepCopyObject(0xc0050ea000)                                                                                                                                                    api     /home/runner/go/pkg/mod/k8s.io/api@v0.23.5/core/v1/zz_generated.deepcopy.go:4898 +0x29 fp=0xc0052976c0 sp=0xc005297688 pc=0x11ed0e9                                                                      api sigs.k8s.io/controller-runtime/pkg/controller/controllerutil.CreateOrUpdate({0x61df030, 0xc0018beb40}, {0x7fc7abe684d8, 0xc003f69180}, {0x6204750, 0xc0050ea000}, 0xc005297940)                              api     /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/controller/controllerutil/controllerutil.go:210 +0x324 fp=0xc0052977f8 sp=0xc0052976c0 pc=0x225bf04                                   api kubegems.io/kubegems/pkg/service/handlers/observability.(*AlertRuleProcessor).syncEmailSecret(0xc000bfa060, {0x61df030, 0xc0018beb40}, 0xc0038c9320)                                                         api     /home/runner/work/kubegems/kubegems/pkg/service/handlers/observability/alert.go:1398 +0x478 fp=0xc005297a68 sp=0xc0052977f8 pc=0x4e4e7b8                                                                 api kubegems.io/kubegems/pkg/service/handlers/observability.(*AlertRuleProcessor).syncLoggingAlertRule(0xc000bfa060, {0x61df030, 0xc0018beb40}, 0xc0038c9320)                                                    api     /home/runner/work/kubegems/kubegems/pkg/service/handlers/observability/alert.go:1577 +0x65 fp=0xc005297ae8 sp=0xc005297a68 pc=0x4e51405                                                                  api kubegems.io/kubegems/pkg/service/handlers/observability.(*AlertRuleProcessor).SyncAlertRule(0xc000bfa060, {0x61df030, 0xc0018beb40}, 0xc0038c9320)                                                           api     /home/runner/work/kubegems/kubegems/pkg/service/handlers/observability/alert.go:1630 +0x12c fp=0xc005297c80 sp=0xc005297ae8 pc=0x4e5230c                                                                 api kubegems.io/kubegems/pkg/service/handlers/observability.(*ObservabilityHandler).syncAlertRulesWithTimeout.func1.1({0x61df030, 0xc0018beb40}, {0x61fb180, 0xc003f69180})                                      api     /home/runner/work/kubegems/kubegems/pkg/service/handlers/observability/alert.go:1835 +0xa5 fp=0xc005297cf8 sp=0xc005297c80 pc=0x4e55f45                                                                  api kubegems.io/kubegems/pkg/service/handlers/base.BaseHandler.Execute({{0x61e42a0, 0xc000897b30}, {0x61eb540, 0xc0006ca810}, {0x61bd940, 0xc000040e20}, 0xc000aad1d0, 0xc0006ca4b0, 0xc000ab8000, 0xc000b0c860, api     /home/runner/work/kubegems/kubegems/pkg/service/handlers/base/base.go:121 +0x136 fp=0xc005297d88 sp=0xc005297cf8 pc=0x48bc136
api kubegems.io/kubegems/pkg/service/handlers/observability.(*ObservabilityHandler).syncAlertRulesWithTimeout.func1(0xc0038c9320)
api     /home/runner/work/kubegems/kubegems/pkg/service/handlers/observability/alert.go:1834 +0x1e5 fp=0xc005297fb8 sp=0xc005297d88 pc=0x4e55c85
api kubegems.io/kubegems/pkg/service/handlers/observability.(*ObservabilityHandler).syncAlertRulesWithTimeout.func2()
api     /home/runner/work/kubegems/kubegems/pkg/service/handlers/observability/alert.go:1841 +0x39 fp=0xc005297fe0 sp=0xc005297fb8 pc=0x4e55a79
api runtime.goexit()
api     /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc005297fe8 sp=0xc005297fe0 pc=0x4725a1
api created by kubegems.io/kubegems/pkg/service/handlers/observability.(*ObservabilityHandler).syncAlertRulesWithTimeout
api     /home/runner/work/kubegems/kubegems/pkg/service/handlers/observability/alert.go:1832 +0x2fb
```

**Comment by LinkMaq** [comment]
https://github.com/kubegems/kubegems/issues/428
